#!/bin/bash

# error precaution.
set -e
# default unzip folder.
DIR='app/main'
mkdir -p "$DIR"

_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO =~ $regex ]]
    then 
        echo "${UPSTREAM_REPO}/archive/alpha.zip"
    else
        echo "https://github.com/code-rgb/USERGE-X/archive/alpha.zip"
    fi
}

_setup_repo(){
    local zippath
    zippath="app/userge-x.zip"
    echo "  Fetching update from Upstream Repo..."
    wget -q $(_get_ziplink) -O "$zippath"
    echo "  Unpacking Data ..."
    unzip -qq "$zippath" -d "$DIR"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    echo "  --- >><< --- Starting [X] --- >><< ---"
    sleep 5
    _startbot
}

_startbot(){
    cd $DIR/*
    bash run
}

_setup_repo