#!bin/bash


# error precaution.
set -e

# cmd.
BUILD_CMD="${BUILD_CMD:-"echo None"}"
INSTALL_CMD="${INSTALL_CMD:-"echo None"}"
LAUNCH_CMD="${LAUNCH_CMD:-"echo None"}"

# default unzip folder.
DIR='app/main'

# default zip file name.
ZIP_FILE_NAME='zipped'

# get zip file from variable.
ZIP_LINK="${ZIP_LINK:-"echo put_your_link_in_variables"}"

# create main directory.
mkdir -p "$DIR"

# fetches latest build.
wget "$ZIP_LINK" -O "app/$ZIP_FILE_NAME.zip"

# unzipping.
unzip "app/$ZIP_FILE_NAME.zip" -d "$DIR"

#run main application.
cd $DIR/*
$BUILD_CMD
$INSTALL_CMD
$LAUNCH_CMD

# stress relief.
sleep 5
